// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txfbxpbsknkfctfzovla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4ZmJ4cGJza25rZmN0ZnpvdmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODIyMDEsImV4cCI6MjA3MDE1ODIwMX0.FyBzO5bztagUXL21XSox0WAXkHhfjyhbYeELnpJnSPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});